-- Knowlu C2 — the whole-branch review's schema and privilege fixes (ruling R-C2-E52).
--
-- Forward-only, like every migration here: 20260911000100…000800 are applied and are never edited
-- (the corrections they carry are comments beside the lines they correct, nothing more). Every
-- schema, privilege and cron change the final review asked for lands here, each under the finding
-- that asked for it.
--
--   C-1  `monthly_spend` was readable with the anon key.
--   S-1  `gmail_queue` was never swept.
--   F-2  `gmail_seen` grew without bound.

-- ---------------------------------------------------------------------------------------------
-- C-1 — the spend view is service-role only.
--
-- `20260911000100_judgment_service.sql:188` created `monthly_spend` with no `security_invoker` and
-- no revoke. A view with neither is a SECURITY DEFINER view — it reads `usage_daily` and `models`
-- as its OWNER, so RLS on `usage_daily` never applies to it — and Supabase grants `select` on a
-- new view to `anon` and `authenticated` exactly as it grants `execute` on a new function. The
-- result was a live read: `GET /rest/v1/monthly_spend` answered 200 to the project's anon key,
-- returning every account's id and its month's inference spend, while C1's `telemetry_daily` —
-- the same shape, but revoked in 20260910000400 — answered 401.
--
-- Revoked rather than switched to `security_invoker = true`: `enforce_budget` reads this view on
-- every model call, and under an invoker view that read would run as the caller and be filtered to
-- nothing by `usage_daily`'s own (policy-less) RLS. The view stays a definer view and simply stops
-- being reachable from a browser; `_shared/judge_caps.ts` reaches it through the service role,
-- which these revokes do not touch.
--
-- `migrations_test.ts`'s view guard is what keeps the next view from repeating this.
revoke all on public.monthly_spend from anon, authenticated;

-- ---------------------------------------------------------------------------------------------
-- S-1 — the gmail queue is swept.
--
-- `gmail_queue` had no sweep at all: a row stayed forever once delivered. Each one carries a
-- model-written title and rationale derived from a student's mail (the comment correction beside
-- the table in 20260911000200 says so), so an unswept queue is an indefinite store of writing
-- about someone's inbox that nothing reads again after the device has pulled it.
--
-- Delivered rows only, and only after seven days: an UNdelivered row is work the device has not
-- collected yet — a laptop that is off for a fortnight must still get its tasks — so it is never
-- touched here. Seven days past delivery is long enough for the device to have been asked twice a
-- day for a week and short enough that nothing lingers.
--
-- 07:31 UTC, beside the other nightly jobs (`knowlu-billing-jobs` at :17, `knowlu-promote-rules`
-- at :17, `knowlu-sweep-google-state` at :23) and deliberately not on the same minute as any of
-- them.
select cron.schedule('knowlu-sweep-gmail-queue', '31 7 * * *', $$delete from public.gmail_queue where delivered_at is not null and delivered_at < now() - interval '7 days';$$);
